### ISSUE TITLE
adapt-to-tf-2.5

### ISSUE THREAD

**Issue by ibrahimoa** [ibrahimoa/tf_developer_certification#1]
### adapt-to-tf-2.5
Review the code and adapt it to `TensorFlow 2.5.` and `Python 3.9` to prepare the certificate exam.

**Due date: 28/07/2021**.

**Comment by ibrahimoa** [comment]
Branch `1-adapt-to-tf-2.5` created to solve this issue.

**Comment by ghost** [comment]
Include **`pandas==1.3.0`** in `requirements.txt` file (used in time series).

**Comment by ibrahimoa** [comment]
Merged into `main` branch. Issue closed.
